services:
  laraveldevelopment:
    image: laraveldevelopment
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace:cached
      - ./.env:/workspace/.env
      - ./Makefile:/workspace/Makefile
    ports:
      - 8000:8000
    pull_policy: never
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example

volumes:
  mysql:
